pipeline:
  build:
    image: node
    commands:
    - npm install
    - CI=false npm run build
  godocker:
    image: plugins/docker
    repo: saleshell/prod
  prod:
    image: saleshell/prod
    datach: true