pipeline:
  build:
    image: node
    commands:
    - npm install
    - CI=false npm run build
  godocker:
    image: plugins/docker
    repo: kysoowjk/saleshell
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    auto_tag: true
  prod:
    image: kysoowjk/saleshell:latest
    datach: true